/*
 * Copyright (C) 2018-2020  LightChaosman
 *
 * BLCMM is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>
 *
 * Additional permission under GNU GPL version 3 section 7:
 *
 * If you modify this Program, or any covered work, by linking or
 * combining it with BLCMM Launcher, BLCMM Lib Distributor, BLCMM
 * Resources, or BLCMM Utilities (or modified versions of those
 * libraries), containing parts covered by the terms of their
 * proprietary license, the licensors of this Program grant you
 * additional permission to convey the resulting work.
 *
 */
package blcmm.gui.panels;

import blcmm.utilities.Utilities;
import blcmm.utilities.options.Option;
import general.utilities.GlobalLogger;
import javax.swing.BoxLayout;

/**
 *
 * @author LightChaosman
 */
public class MasterSettingsPanel extends javax.swing.JPanel {

    private final ToolSettingsPanel toolSettingsPanel;
    private final UpdateSettingsPanel updateSettingsPanel;
    private final ToolSettingsPanel dangerousSettingsPanel;

    /**
     * Creates new form MasterSettingsPanel
     */
    public MasterSettingsPanel() {
        GlobalLogger.log("Opened Master settings Panel");
        initComponents();

        toolSettingsPanel = new ToolSettingsPanel(Option.Shown.SETTINGS, masterSettingsTabbedPane);
        toolSettingsPanel.setSize(generalSettingsGuiPanel.getSize());
        generalSettingsGuiPanel.setLayout(new BoxLayout(generalSettingsGuiPanel, BoxLayout.PAGE_AXIS));
        generalSettingsGuiPanel.add(toolSettingsPanel);

        updateSettingsPanel = new UpdateSettingsPanel();
        updateSettingsPanel.setSize(autoupdateSettingsGuiPanel.getSize());
        autoupdateSettingsGuiPanel.setLayout(new BoxLayout(autoupdateSettingsGuiPanel, BoxLayout.PAGE_AXIS));
        autoupdateSettingsGuiPanel.add(updateSettingsPanel);
        
        dangerousSettingsPanel = new ToolSettingsPanel(Option.Shown.DANGEROUS, masterSettingsTabbedPane,
            "The settings on this screen should be left alone unless you know<br/>"
            + "exactly what they do, and have a strong need to do so."
        );
        dangerousSettingsPanel.setSize(dangerousSettingsGuiPanel.getSize());
        dangerousSettingsGuiPanel.setLayout(new BoxLayout(dangerousSettingsGuiPanel, BoxLayout.PAGE_AXIS));
        dangerousSettingsGuiPanel.add(dangerousSettingsPanel);

        generalSettingsGuiScrollPane.getVerticalScrollBar().setUnitIncrement(16);
        autoupdateSettingsGuiScrollPane.getVerticalScrollBar().setUnitIncrement(16);
        dangerousSettingsGuiScrollPane.getVerticalScrollBar().setUnitIncrement(16);

        Utilities.makeWindowOfComponentResizable(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        masterSettingsTabbedPane = new javax.swing.JTabbedPane();
        generalSettingsGuiScrollPane = new javax.swing.JScrollPane();
        generalSettingsGuiPanel = new javax.swing.JPanel();
        autoupdateSettingsGuiScrollPane = new javax.swing.JScrollPane();
        autoupdateSettingsGuiPanel = new javax.swing.JPanel();
        dangerousSettingsGuiScrollPane = new javax.swing.JScrollPane();
        dangerousSettingsGuiPanel = new javax.swing.JPanel();

        masterSettingsTabbedPane.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout generalSettingsGuiPanelLayout = new javax.swing.GroupLayout(generalSettingsGuiPanel);
        generalSettingsGuiPanel.setLayout(generalSettingsGuiPanelLayout);
        generalSettingsGuiPanelLayout.setHorizontalGroup(
            generalSettingsGuiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 507, Short.MAX_VALUE)
        );
        generalSettingsGuiPanelLayout.setVerticalGroup(
            generalSettingsGuiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 314, Short.MAX_VALUE)
        );

        generalSettingsGuiScrollPane.setViewportView(generalSettingsGuiPanel);

        masterSettingsTabbedPane.addTab("General settings", generalSettingsGuiScrollPane);

        javax.swing.GroupLayout autoupdateSettingsGuiPanelLayout = new javax.swing.GroupLayout(autoupdateSettingsGuiPanel);
        autoupdateSettingsGuiPanel.setLayout(autoupdateSettingsGuiPanelLayout);
        autoupdateSettingsGuiPanelLayout.setHorizontalGroup(
            autoupdateSettingsGuiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 507, Short.MAX_VALUE)
        );
        autoupdateSettingsGuiPanelLayout.setVerticalGroup(
            autoupdateSettingsGuiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 314, Short.MAX_VALUE)
        );

        autoupdateSettingsGuiScrollPane.setViewportView(autoupdateSettingsGuiPanel);

        masterSettingsTabbedPane.addTab("Autoupdate settings", autoupdateSettingsGuiScrollPane);

        javax.swing.GroupLayout dangerousSettingsGuiPanelLayout = new javax.swing.GroupLayout(dangerousSettingsGuiPanel);
        dangerousSettingsGuiPanel.setLayout(dangerousSettingsGuiPanelLayout);
        dangerousSettingsGuiPanelLayout.setHorizontalGroup(
            dangerousSettingsGuiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 523, Short.MAX_VALUE)
        );
        dangerousSettingsGuiPanelLayout.setVerticalGroup(
            dangerousSettingsGuiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 307, Short.MAX_VALUE)
        );

        dangerousSettingsGuiScrollPane.setViewportView(dangerousSettingsGuiPanel);

        masterSettingsTabbedPane.addTab("Dangerous settings", dangerousSettingsGuiScrollPane);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(masterSettingsTabbedPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(masterSettingsTabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 344, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel autoupdateSettingsGuiPanel;
    private javax.swing.JScrollPane autoupdateSettingsGuiScrollPane;
    private javax.swing.JPanel dangerousSettingsGuiPanel;
    private javax.swing.JScrollPane dangerousSettingsGuiScrollPane;
    private javax.swing.JPanel generalSettingsGuiPanel;
    private javax.swing.JScrollPane generalSettingsGuiScrollPane;
    private javax.swing.JTabbedPane masterSettingsTabbedPane;
    // End of variables declaration//GEN-END:variables

    public boolean needsLauncherReset() {
        return updateSettingsPanel.needsLauncherReset();
    }

    public boolean needsToolReset() {
        return toolSettingsPanel.needsToolReset() || dangerousSettingsPanel.needsToolReset();
    }

    public boolean needsTreeResize() {
        return toolSettingsPanel.needsTreeResize() || dangerousSettingsPanel.needsTreeResize();
    }

    public UpdateSettingsPanel getUpdatePanel() {
        return updateSettingsPanel;
    }

    public void focusToUpdatePanel() {
        masterSettingsTabbedPane.setSelectedIndex(1);
    }
}
